language: java
jdk:
  - oraclejdk8

sudo: false

cache:
  directories:
    - $HOME/.gradle

script:
  - ./gradlew test

# https://github.com/travis-ci/travis-ci/issues/3259
addons:
  apt:
    packages:
      - oracle-java8-installer
